{
    "version": "2",
    "templates": [
        {
            "type": 1,
            "title": "BusyBox",
            "description": "Busybox base image",
            "name": "docker-busybox",
            "version": "1.34.1",
            "logo": "",
            "platform": "linux",
            "categories": [
                "operating-system"
            ],
            "image": "busybox:1.34.1"
        },
        {
            "type": 1,
            "title": "Ubuntu Desktop with noVNC test",
            "description": "Remote desktop Sharing in Ubuntu 20.04",
            "name": "docker-ubuntu-novnc",
            "version": "20.04",
            "logo": "https://raw.githubusercontent.com/qnap-dev/container-apps/2.0/images/ubuntu_icon.png",
            "platform": "linux/amd64",
            "categories": [
                "operating-system"
            ],
            "image": "dorowu/ubuntu-desktop-lxde-vnc:focal"
        }
    ]
}
